# Generated by Django 5.0.6 on 2024-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('admission', models.CharField(max_length=255)),
                ('course_duration', models.IntegerField()),
                ('affiliation', models.CharField(max_length=255)),
                ('placement', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('ranking', models.CharField(max_length=255)),
                ('hostel', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('admission_till_date', models.DateField()),
            ],
        ),
    ]
