# Generated by Django 5.0.6 on 2024-08-08 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='dean_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='is_in_top_ten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='college',
            name='course_duration',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='college',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
